baseURL: https://HowardHsuuu.github.io/
languageCode: en-us
defaultContentLanguage: en-us
title: Notes
#title: Howard's Blog
pagination:
  PagerSize: 5
theme: PaperMod
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  en-us:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
#        - name: Search
#          url: search/
#          weight: 20
        - name: Topics
          url: posts/
          weight: 10
        - name: About Me
          url: aboutme/
          weight: 20
        - name: Tags
          url: tags
          weight: 15
  zh-hant:
    languageName: "Traditional Chinese"
    disabled: true
params:
  env: production
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButton: true
  social: true
  assets:
    favicon: /images/icon.png
    favicon16x16: /images/icon-16x16.png
    favicon32x32: /images/icon-32x32.png
    apple_touch_icon: /images/icon.png
    safari_pinned_tab: /images/icon.png
  label:
    #text: Howard's Blog
    text: Notes
    icon: /images/icon.png
    iconHeight: 35
  homeInfoParams:
    Title: Hi, I'm Howard Hsu.
    Content: A student at National Taiwan University (NTU), majoring in Computer Science. My research interests span AI, robotics, computational neuroscience, quantum computing, and defi security.
  socialIcons:
    - name: "github"
      url: "https://github.com/HowardHsuuu"

output:
  home:
    - HTML
    - RSS
    - JSON
